In [13]:
#import sys
#sys.path.append('../input/pytorch-image-models/pytorch-image-models-master')

import collections
import gc
import json
import os
import random
import time
import warnings
warnings.simplefilter("ignore")

from albumentations import *
from albumentations.pytorch import ToTensor
import cv2
from imblearn.under_sampling import RandomUnderSampler
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
from PIL import Image, ImageFilter
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
#import tifffile as tiff
import timm
import torch
import torch.backends.cudnn as cudnn
import torch.nn as nn
from torch.nn import functional as F
import torch.optim as optim
from torch.optim.lr_scheduler import ReduceLROnPlateau
from torch.utils.data import DataLoader, Dataset, sampler
from tqdm import tqdm_notebook as tqdm

import s3fs
fs = s3fs.S3FileSystem()
prefix = f's3://wildcamdata'

%matplotlib inline

### setting

In [14]:
DATASET = os.path.join(prefix, '~/')
CROPED_DATA = '256x256/'

TRAIN_CROPED_DATA = os.path.join(CROPED_DATA, "croped_images_train/")
TEST_CROPED_DATA = os.path.join(CROPED_DATA, "croped_images_test/")

In [15]:
BATCH_SIZE = 32
DEVICE = ('cuda' if torch.cuda.is_available() else 'cpu')
EPOCHS = 5000
NUM_WORKERS = 4
SEED = 2021

In [18]:
def set_seed(seed=2**3):
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)
    torch.backends.cudnn.deterministic = True
set_seed(SEED)

In [19]:
df_croped_img_ids_train = pd.read_csv(CROPED_DATA + "croped_train.csv")
df_croped_img_ids_test = pd.read_csv(CROPED_DATA + "croped_test.csv")

In [20]:
df_croped_img_ids_train.head()

                                     id  idx  category_id
0  905a3c8c-21bc-11ea-a13a-137349068a90    1          374
1  905a4416-21bc-11ea-a13a-137349068a90    1           97
2  905a4416-21bc-11ea-a13a-137349068a90    2           97
3  905a4416-21bc-11ea-a13a-137349068a90    3           97
4  905a579e-21bc-11ea-a13a-137349068a90    1           90

In [21]:
df_croped_img_ids_test.head()

                                     id  idx
0  915879a0-21bc-11ea-a13a-137349068a90    1
1  91588116-21bc-11ea-a13a-137349068a90    1
2  9158a2f4-21bc-11ea-a13a-137349068a90    1
3  9158aaa6-21bc-11ea-a13a-137349068a90    1
4  9158f1a0-21bc-11ea-a13a-137349068a90    1

### create train dataframe

In [27]:
with fs.open(os.path.join(DATASET, 'metadata/iwildcam2021_train_annotations.json'), encoding='utf-8') as json_file:
    train_annotations =json.load(json_file)
df_train_annotation = pd.DataFrame(train_annotations["annotations"])

In [28]:
train = df_croped_img_ids_train[["id", "idx"]].merge(df_train_annotation[["image_id", "category_id"]], 
                                      left_on='id', right_on='image_id')[["id", "idx", "category_id"]]

In [29]:
df_categories = pd.DataFrame(train_annotations["categories"])

In [30]:
cat_idxs = df_categories["id"]

def convert_cat_to_index(x):
    return np.where(cat_idxs==x)[0][0]

In [31]:
train["category_id"] = train["category_id"].map(lambda x: convert_cat_to_index(x))

In [32]:
train.head()

                                     id  idx  category_id
0  905a3c8c-21bc-11ea-a13a-137349068a90    1          164
1  905a4416-21bc-11ea-a13a-137349068a90    1           39
2  905a4416-21bc-11ea-a13a-137349068a90    2           39
3  905a4416-21bc-11ea-a13a-137349068a90    3           39
4  905a579e-21bc-11ea-a13a-137349068a90    1           34

# Train

## Create dataset for training

In [33]:
# ====================================================
# Dataset for train
# ====================================================

mean = np.array([0.37087523, 0.370876, 0.3708759] )
std = np.array([0.21022698, 0.21022713, 0.21022706])

def img2tensor(img,dtype:np.dtype=np.float32):
    if img.ndim==2 : img = np.expand_dims(img,2)
    img = np.transpose(img,(2,0,1))
    return torch.from_numpy(img.astype(dtype, copy=False))

class IWildcamTrainDataset(Dataset):
    def __init__(self, df, tfms=None):
        self.ids = df["id"]
        self.idxs = df["idx"]
        self.categories = df["category_id"]
        self.tfms = tfms
        
    def __len__(self):
        return len(self.ids)
    
    def __getitem__(self, idx):
        size = (256, 256)
        image_id = self.ids[idx]
        image_idx = self.idxs[idx]
        iamge_categorie = self.categories[idx]
        
        image_path = TRAIN_CROPED_DATA + f"{image_id}_{image_idx}.jpg"
        img = cv2.resize(cv2.cvtColor(cv2.imread(image_path), cv2.COLOR_BGR2RGB),size)

        if self.tfms is not None:
            augmented = self.tfms(image=img)
            img = augmented['image']
            
        # we should normalize here
        return img2tensor((img/255.0  - mean)/std), torch.tensor(iamge_categorie)

In [34]:
def get_aug(p=1.0):
    return Compose([
        HorizontalFlip(),
        ShiftScaleRotate(shift_limit=0.0625, scale_limit=0.2, rotate_limit=15, p=0.9, 
                         border_mode=cv2.BORDER_REFLECT),
        VerticalFlip(),
        RandomBrightnessContrast(p=0.9),
    ], p=p)

## Create model

In [35]:
# ====================================================
# EfficientNet Model
# ====================================================

class enet_v2(nn.Module):

    def __init__(self, backbone, out_dim, pretrained=False):
        super(enet_v2, self).__init__()
        self.enet = timm.create_model(backbone, pretrained=pretrained)
        in_ch = self.enet.classifier.in_features
        self.myfc = nn.Linear(in_ch, out_dim)
        self.enet.classifier = nn.Identity()

    def forward(self, x):
        x = self.enet(x)
        x = self.myfc(x)
        return x

In [36]:
model = enet_v2(backbone="tf_efficientnet_b0", out_dim=205)
model.to(DEVICE)

enet_v2(
  (enet): EfficientNet(
    (conv_stem): Conv2dSame(3, 32, kernel_size=(3, 3), stride=(2, 2), bias=False)
    (bn1): BatchNorm2d(32, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
    (act1): SwishMe()
    (blocks): Sequential(
      (0): Sequential(
        (0): DepthwiseSeparableConv(
          (conv_dw): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32, bias=False)
          (bn1): BatchNorm2d(32, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(32, 8, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(8, 32, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pw): Conv2d(32, 16, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn2): BatchNorm2d(16, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): Identity()
        )
      )
      (1): Sequential(
        (0): InvertedResidual(
          (conv_pw): Conv2d(16, 96, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(96, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2dSame(96, 96, kernel_size=(3, 3), stride=(2, 2), groups=96, bias=False)
          (bn2): BatchNorm2d(96, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(96, 4, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(4, 96, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(96, 24, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(24, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (1): InvertedResidual(
          (conv_pw): Conv2d(24, 144, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(144, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2d(144, 144, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=144, bias=False)
          (bn2): BatchNorm2d(144, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(144, 6, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(6, 144, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(144, 24, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(24, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (2): Sequential(
        (0): InvertedResidual(
          (conv_pw): Conv2d(24, 144, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(144, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2dSame(144, 144, kernel_size=(5, 5), stride=(2, 2), groups=144, bias=False)
          (bn2): BatchNorm2d(144, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(144, 6, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(6, 144, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(144, 40, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(40, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (1): InvertedResidual(
          (conv_pw): Conv2d(40, 240, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(240, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2d(240, 240, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=240, bias=False)
          (bn2): BatchNorm2d(240, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(240, 10, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(10, 240, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(240, 40, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(40, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (3): Sequential(
        (0): InvertedResidual(
          (conv_pw): Conv2d(40, 240, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(240, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2dSame(240, 240, kernel_size=(3, 3), stride=(2, 2), groups=240, bias=False)
          (bn2): BatchNorm2d(240, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(240, 10, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(10, 240, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(240, 80, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(80, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (1): InvertedResidual(
          (conv_pw): Conv2d(80, 480, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(480, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2d(480, 480, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=480, bias=False)
          (bn2): BatchNorm2d(480, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(480, 20, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(20, 480, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(480, 80, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(80, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (2): InvertedResidual(
          (conv_pw): Conv2d(80, 480, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(480, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2d(480, 480, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=480, bias=False)
          (bn2): BatchNorm2d(480, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(480, 20, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(20, 480, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(480, 80, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(80, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (4): Sequential(
        (0): InvertedResidual(
          (conv_pw): Conv2d(80, 480, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(480, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2d(480, 480, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=480, bias=False)
          (bn2): BatchNorm2d(480, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(480, 20, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(20, 480, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(480, 112, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(112, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (1): InvertedResidual(
          (conv_pw): Conv2d(112, 672, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(672, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2d(672, 672, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=672, bias=False)
          (bn2): BatchNorm2d(672, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(672, 28, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(28, 672, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(672, 112, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(112, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (2): InvertedResidual(
          (conv_pw): Conv2d(112, 672, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(672, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2d(672, 672, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=672, bias=False)
          (bn2): BatchNorm2d(672, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(672, 28, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(28, 672, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(672, 112, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(112, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (5): Sequential(
        (0): InvertedResidual(
          (conv_pw): Conv2d(112, 672, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(672, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2dSame(672, 672, kernel_size=(5, 5), stride=(2, 2), groups=672, bias=False)
          (bn2): BatchNorm2d(672, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(672, 28, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(28, 672, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(672, 192, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(192, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (1): InvertedResidual(
          (conv_pw): Conv2d(192, 1152, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(1152, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2d(1152, 1152, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=1152, bias=False)
          (bn2): BatchNorm2d(1152, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(1152, 48, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(48, 1152, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(1152, 192, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(192, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (2): InvertedResidual(
          (conv_pw): Conv2d(192, 1152, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(1152, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2d(1152, 1152, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=1152, bias=False)
          (bn2): BatchNorm2d(1152, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(1152, 48, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(48, 1152, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(1152, 192, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(192, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (3): InvertedResidual(
          (conv_pw): Conv2d(192, 1152, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(1152, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2d(1152, 1152, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=1152, bias=False)
          (bn2): BatchNorm2d(1152, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(1152, 48, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(48, 1152, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(1152, 192, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(192, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (6): Sequential(
        (0): InvertedResidual(
          (conv_pw): Conv2d(192, 1152, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(1152, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2d(1152, 1152, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=1152, bias=False)
          (bn2): BatchNorm2d(1152, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(1152, 48, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(48, 1152, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(1152, 320, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(320, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
    )
    (conv_head): Conv2d(320, 1280, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (bn2): BatchNorm2d(1280, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
    (act2): SwishMe()
    (global_pool): SelectAdaptivePool2d (pool_type=avg, flatten=True)
    (classifier): Identity()
  )
  (myfc): Linear(in_features=1280, out_features=205, bias=True)
)

## train setting

In [37]:
# ====================================================
# Optimizer and Loss
# ====================================================

optimizer = torch.optim.SGD(model.parameters(), lr=0.0001, momentum=0.9)
#optimizer = torch.optim.SGD([
#                {'params': model.parameters()},
#               {'params': model.classifier.parameters(), 'lr': 1e-4}
#            ], lr=1e-3, momentum=0.9)
criterion = nn.CrossEntropyLoss()

## Train

Since we know that [the training data is imbalanced](https://www.kaggle.com/nayuts/iwildcam-2021-overviewing-for-start#EDA), I undersampled it.

In [38]:
rus = RandomUnderSampler(random_state=SEED, replacement=True)

def generate_dataloders(train):
    
    train_resampled, _ = rus.fit_resample(train, train["category_id"])
    test_resampled, _ = rus.fit_resample(train, train["category_id"])

    train_resampled = train_resampled.reset_index(drop=True)
    test_resampled = test_resampled.reset_index(drop=True)
    
    ds_train = IWildcamTrainDataset(train_resampled, tfms=get_aug())
    dl_train = DataLoader(ds_train,batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS)
    ds_test = IWildcamTrainDataset(test_resampled)
    dl_test = DataLoader(ds_test,batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS)
    
    return dl_train, dl_test

In [39]:
# ====================================================
# Train
# ====================================================

for epoch in tqdm(range(EPOCHS)):
    
    dl_train, dl_test = generate_dataloders(train)
    
    ###Train
    model.train()
    train_loss = 0
    
    for data in dl_train:
        optimizer.zero_grad()
        imgs, categories = data
        imgs = imgs.to(DEVICE)
        categories = categories.to(DEVICE)
        
        outputs = model(imgs)
    
        loss = criterion(outputs, categories)
        loss.backward()
        optimizer.step()
            
        train_loss += loss.item()
    train_loss /= len(dl_train)
        
    print(f"EPOCH: {epoch + 1}, train_loss: {train_loss}")
        
    ###Validation
    model.eval()
    valid_loss = 0
        
    for data in dl_test:
        imgs, categories = data
        imgs = imgs.to(DEVICE)
        categories = categories.to(DEVICE)
        
        outputs = model(imgs)
    
        loss = criterion(outputs, categories)
        
        valid_loss += loss.item()
    valid_loss /= len(dl_test)
        
    print(f"EPOCH: {epoch + 1}, valid_loss: {valid_loss}")
        
    
    if (epoch+1)%50 == 0 or (epoch+1)%EPOCHS == 0:
        ###Save model
        torch.save(model.state_dict(), f"{epoch+1}_.pth")

  0%|          | 0/5000 [00:00<?, ?it/s]

EPOCH: 1, train_loss: 5.322283676692417
EPOCH: 1, valid_loss: 5.323815209524972
EPOCH: 2, train_loss: 5.340143612452915
EPOCH: 2, valid_loss: 5.324080126626151
EPOCH: 3, train_loss: 5.343122686658587
EPOCH: 3, valid_loss: 5.324506827763149
EPOCH: 4, train_loss: 5.312050070081439
EPOCH: 4, valid_loss: 5.324557100023542
EPOCH: 5, train_loss: 5.311058112553188
EPOCH: 5, valid_loss: 5.325109686170306
EPOCH: 6, train_loss: 5.315532548086984
EPOCH: 6, valid_loss: 5.321225915636335
EPOCH: 7, train_loss: 5.307747568402972
EPOCH: 7, valid_loss: 5.304570743015835
EPOCH: 8, train_loss: 5.301833357129778
EPOCH: 8, valid_loss: 5.290436676570347
EPOCH: 9, train_loss: 5.297598089490618
EPOCH: 9, valid_loss: 5.271810735974993
EPOCH: 10, train_loss: 5.291649750300816
EPOCH: 10, valid_loss: 5.264403683798654
EPOCH: 11, train_loss: 5.267889976501465
EPOCH: 11, valid_loss: 5.247072764805385
EPOCH: 12, train_loss: 5.2777373450143
EPOCH: 12, valid_loss: 5.254645551953997
EPOCH: 13, train_loss: 5.29563079561506
EPOCH: 13, valid_loss: 5.229897635323661
EPOCH: 14, train_loss: 5.266217299870083
EPOCH: 14, valid_loss: 5.210300990513393
EPOCH: 15, train_loss: 5.267209666115897
EPOCH: 15, valid_loss: 5.206711905343192
EPOCH: 16, train_loss: 5.27233852658953
EPOCH: 16, valid_loss: 5.204251766204834
EPOCH: 17, train_loss: 5.258643422807966
EPOCH: 17, valid_loss: 5.196860177176339
EPOCH: 18, train_loss: 5.259975501469204
EPOCH: 18, valid_loss: 5.17088999067034
EPOCH: 19, train_loss: 5.246976443699428
EPOCH: 19, valid_loss: 5.155407088143485
EPOCH: 20, train_loss: 5.246603352682931
EPOCH: 20, valid_loss: 5.133826528276716
EPOCH: 21, train_loss: 5.231350149427142
EPOCH: 21, valid_loss: 5.151686259678432
EPOCH: 22, train_loss: 5.252703871045794
EPOCH: 22, valid_loss: 5.127810546330044
EPOCH: 23, train_loss: 5.260455063411167
EPOCH: 23, valid_loss: 5.111658845629011
EPOCH: 24, train_loss: 5.2367649759565085
EPOCH: 24, valid_loss: 5.137130669185093
EPOCH: 25, train_loss: 5.226695196969168
EPOCH: 25, valid_loss: 5.144067083086286
EPOCH: 26, train_loss: 5.226794379098075
EPOCH: 26, valid_loss: 5.138814721788679
EPOCH: 27, train_loss: 5.2394779069083075
EPOCH: 27, valid_loss: 5.145655359540667
EPOCH: 28, train_loss: 5.225596564156668
EPOCH: 28, valid_loss: 5.138575281415667
EPOCH: 29, train_loss: 5.214484078543527
EPOCH: 29, valid_loss: 5.146375588008335
EPOCH: 30, train_loss: 5.214861120496478
EPOCH: 30, valid_loss: 5.132369926997593
EPOCH: 31, train_loss: 5.2141304697309225
EPOCH: 31, valid_loss: 5.1317266055515836
EPOCH: 32, train_loss: 5.21230833871024
EPOCH: 32, valid_loss: 5.140842233385358
EPOCH: 33, train_loss: 5.195337976728167
EPOCH: 33, valid_loss: 5.140046392168317
EPOCH: 34, train_loss: 5.205921036856515
EPOCH: 34, valid_loss: 5.1328125
EPOCH: 35, train_loss: 5.22260502406529
EPOCH: 35, valid_loss: 5.113527434212821
EPOCH: 36, train_loss: 5.186164174761091
EPOCH: 36, valid_loss: 5.129504203796387
EPOCH: 37, train_loss: 5.211197989327567
EPOCH: 37, valid_loss: 5.103927067347935
EPOCH: 38, train_loss: 5.193238326481411
EPOCH: 38, valid_loss: 5.127631528036935
EPOCH: 39, train_loss: 5.221008913857596
EPOCH: 39, valid_loss: 5.125439711979458
EPOCH: 40, train_loss: 5.20266056060791
EPOCH: 40, valid_loss: 5.131524699074881
EPOCH: 41, train_loss: 5.199920858655657
EPOCH: 41, valid_loss: 5.132978439331055
EPOCH: 42, train_loss: 5.1850457191467285
EPOCH: 42, valid_loss: 5.130150658743722
EPOCH: 43, train_loss: 5.193298884800503
EPOCH: 43, valid_loss: 5.1026129722595215
EPOCH: 44, train_loss: 5.187228202819824
EPOCH: 44, valid_loss: 5.13005931036813
EPOCH: 45, train_loss: 5.192222663334438
EPOCH: 45, valid_loss: 5.10188797542027
EPOCH: 46, train_loss: 5.189389433179583
EPOCH: 46, valid_loss: 5.089149134499686
EPOCH: 47, train_loss: 5.179772649492536
EPOCH: 47, valid_loss: 5.100036484854562
EPOCH: 48, train_loss: 5.1760366303580145
EPOCH: 48, valid_loss: 5.100907189505441
EPOCH: 49, train_loss: 5.180956091199603
EPOCH: 49, valid_loss: 5.104897975921631
EPOCH: 50, train_loss: 5.1781439781188965
EPOCH: 50, valid_loss: 5.109998158046177
EPOCH: 51, train_loss: 5.164918422698975
EPOCH: 51, valid_loss: 5.091848169054304
EPOCH: 52, train_loss: 5.178179809025356
EPOCH: 52, valid_loss: 5.093938146318708
EPOCH: 53, train_loss: 5.160130092075893
EPOCH: 53, valid_loss: 5.096186024802072
EPOCH: 54, train_loss: 5.165573801313128
EPOCH: 54, valid_loss: 5.0962685857500345
EPOCH: 55, train_loss: 5.158406598227365
EPOCH: 55, valid_loss: 5.127672127314976
EPOCH: 56, train_loss: 5.156718526567731
EPOCH: 56, valid_loss: 5.110469000680106
EPOCH: 57, train_loss: 5.168987614767892
EPOCH: 57, valid_loss: 5.114956447056362
EPOCH: 58, train_loss: 5.15727846963065
EPOCH: 58, valid_loss: 5.086530685424805
EPOCH: 59, train_loss: 5.148133346012661
EPOCH: 59, valid_loss: 5.070371764046805
EPOCH: 60, train_loss: 5.152900559561593
EPOCH: 60, valid_loss: 5.078516006469727
EPOCH: 61, train_loss: 5.148273876735142
EPOCH: 61, valid_loss: 5.083189419337681
EPOCH: 62, train_loss: 5.147237232753208
EPOCH: 62, valid_loss: 5.088626997811454
EPOCH: 63, train_loss: 5.152745042528425
EPOCH: 63, valid_loss: 5.102553708212716
EPOCH: 64, train_loss: 5.14284256526402
EPOCH: 64, valid_loss: 5.0526270525796075
EPOCH: 65, train_loss: 5.146468094417027
EPOCH: 65, valid_loss: 5.05770206451416
EPOCH: 66, train_loss: 5.140609196254185
EPOCH: 66, valid_loss: 5.062265123639788
EPOCH: 67, train_loss: 5.147650786808559
EPOCH: 67, valid_loss: 5.0607830456324985
EPOCH: 68, train_loss: 5.126325198582241
EPOCH: 68, valid_loss: 5.082658427102225
EPOCH: 69, train_loss: 5.150264603751046
EPOCH: 69, valid_loss: 5.0802811895098
EPOCH: 70, train_loss: 5.145172255379813
EPOCH: 70, valid_loss: 5.041990382330758
EPOCH: 71, train_loss: 5.135658877236502
EPOCH: 71, valid_loss: 5.076633657727923
EPOCH: 72, train_loss: 5.132376057761056
EPOCH: 72, valid_loss: 5.068592718669346
EPOCH: 73, train_loss: 5.131839071001325
EPOCH: 73, valid_loss: 5.067315987178257
EPOCH: 74, train_loss: 5.1304731369018555
EPOCH: 74, valid_loss: 5.064052649906704
EPOCH: 75, train_loss: 5.12082440512521
EPOCH: 75, valid_loss: 5.0541567121233255
EPOCH: 76, train_loss: 5.115224157060895
EPOCH: 76, valid_loss: 5.049733638763428
EPOCH: 77, train_loss: 5.126550538199289
EPOCH: 77, valid_loss: 5.090310982295445
EPOCH: 78, train_loss: 5.137671334402902
EPOCH: 78, valid_loss: 5.084714140210833
EPOCH: 79, train_loss: 5.14928708757673
EPOCH: 79, valid_loss: 5.076485429491315
EPOCH: 80, train_loss: 5.1174635887146
EPOCH: 80, valid_loss: 5.067217213766916
EPOCH: 81, train_loss: 5.117762838091169
EPOCH: 81, valid_loss: 5.078713757651193
EPOCH: 82, train_loss: 5.130675111498151
EPOCH: 82, valid_loss: 5.0661464759281705
EPOCH: 83, train_loss: 5.11909988948277
EPOCH: 83, valid_loss: 5.062252180916922
EPOCH: 84, train_loss: 5.123753820146833
EPOCH: 84, valid_loss: 5.060689619609287
EPOCH: 85, train_loss: 5.100279331207275
EPOCH: 85, valid_loss: 5.057587146759033
EPOCH: 86, train_loss: 5.0966724668230325
EPOCH: 86, valid_loss: 5.069517442158291
EPOCH: 87, train_loss: 5.132491247994559
EPOCH: 87, valid_loss: 5.078042847769601
EPOCH: 88, train_loss: 5.097770622798374
EPOCH: 88, valid_loss: 5.074009929384504
EPOCH: 89, train_loss: 5.09287657056536
EPOCH: 89, valid_loss: 5.049982309341431
EPOCH: 90, train_loss: 5.111331462860107
EPOCH: 90, valid_loss: 5.053146634783063
EPOCH: 91, train_loss: 5.1062412943158835
EPOCH: 91, valid_loss: 5.0602303232465475
EPOCH: 92, train_loss: 5.098916121891567
EPOCH: 92, valid_loss: 5.060645137514387
EPOCH: 93, train_loss: 5.1048127583095
EPOCH: 93, valid_loss: 5.06187721661159
EPOCH: 94, train_loss: 5.104866709027972
EPOCH: 94, valid_loss: 5.0502795832497736
EPOCH: 95, train_loss: 5.1132298197065085
EPOCH: 95, valid_loss: 5.058983189719064
EPOCH: 96, train_loss: 5.119030475616455
EPOCH: 96, valid_loss: 5.069415160587856
EPOCH: 97, train_loss: 5.10155725479126
EPOCH: 97, valid_loss: 5.070145879473005
EPOCH: 98, train_loss: 5.131509576525007
EPOCH: 98, valid_loss: 5.063549927302769
EPOCH: 99, train_loss: 5.1168075970241
EPOCH: 99, valid_loss: 5.052052804401943
EPOCH: 100, train_loss: 5.103008474622454
EPOCH: 100, valid_loss: 5.0524391787392755
EPOCH: 101, train_loss: 5.097867897578648
EPOCH: 101, valid_loss: 5.044185161590576
EPOCH: 102, train_loss: 5.082543849945068
EPOCH: 102, valid_loss: 5.032296691622053
EPOCH: 103, train_loss: 5.093819209507534
EPOCH: 103, valid_loss: 5.022753545216152
EPOCH: 104, train_loss: 5.103570801871164
EPOCH: 104, valid_loss: 5.04060697555542
EPOCH: 105, train_loss: 5.109012944357736
EPOCH: 105, valid_loss: 5.02924462727138
EPOCH: 106, train_loss: 5.098652158464704
EPOCH: 106, valid_loss: 5.023180280412946
EPOCH: 107, train_loss: 5.090461117880685
EPOCH: 107, valid_loss: 5.039274283817837
EPOCH: 108, train_loss: 5.089351040976388
EPOCH: 108, valid_loss: 5.054373366492135
EPOCH: 109, train_loss: 5.073925495147705
EPOCH: 109, valid_loss: 5.032788140433175
EPOCH: 110, train_loss: 5.110422679356167
EPOCH: 110, valid_loss: 5.056527955191476
EPOCH: 111, train_loss: 5.066812719617571
EPOCH: 111, valid_loss: 5.057884080069406
EPOCH: 112, train_loss: 5.096034254346575
EPOCH: 112, valid_loss: 5.038613387516567
EPOCH: 113, train_loss: 5.074766908373151
EPOCH: 113, valid_loss: 5.0391320160457065
EPOCH: 114, train_loss: 5.0835708890642435
EPOCH: 114, valid_loss: 5.049609388623919
EPOCH: 115, train_loss: 5.055727345602853
EPOCH: 115, valid_loss: 5.04415546144758
EPOCH: 116, train_loss: 5.070558820452009
EPOCH: 116, valid_loss: 5.05153785433088
EPOCH: 117, train_loss: 5.077345098767962
EPOCH: 117, valid_loss: 5.014339515141079
EPOCH: 118, train_loss: 5.082043852124896
EPOCH: 118, valid_loss: 5.02090174811227
EPOCH: 119, train_loss: 5.096746376582554
EPOCH: 119, valid_loss: 5.013785634722028
EPOCH: 120, train_loss: 5.089764254433768
EPOCH: 120, valid_loss: 5.012885843004499
EPOCH: 121, train_loss: 5.056784697941372
EPOCH: 121, valid_loss: 5.001251220703125
EPOCH: 122, train_loss: 5.067033154623849
EPOCH: 122, valid_loss: 4.977002211979458
EPOCH: 123, train_loss: 5.087762764522007
EPOCH: 123, valid_loss: 5.007610593523298
EPOCH: 124, train_loss: 5.08493287222726
EPOCH: 124, valid_loss: 5.00865295955113
EPOCH: 125, train_loss: 5.087820053100586
EPOCH: 125, valid_loss: 5.031095266342163
EPOCH: 126, train_loss: 5.076121602739606
EPOCH: 126, valid_loss: 5.036265066691807
EPOCH: 127, train_loss: 5.057405539921352
EPOCH: 127, valid_loss: 5.070773431232998
EPOCH: 128, train_loss: 5.043579714638846
EPOCH: 128, valid_loss: 5.071759360177176
EPOCH: 129, train_loss: 5.085260731833322
EPOCH: 129, valid_loss: 5.050258466175625
EPOCH: 130, train_loss: 5.0909046445574075
EPOCH: 130, valid_loss: 5.072002410888672
EPOCH: 131, train_loss: 5.0799729483468195
EPOCH: 131, valid_loss: 5.044396911348615
EPOCH: 132, train_loss: 5.053820473807199
EPOCH: 132, valid_loss: 5.076666082654681
EPOCH: 133, train_loss: 5.063203402927944
EPOCH: 133, valid_loss: 5.117452825818743
EPOCH: 134, train_loss: 5.058604512895856
EPOCH: 134, valid_loss: 5.083968877792358
EPOCH: 135, train_loss: 5.04686839239938
EPOCH: 135, valid_loss: 5.084364550454276
EPOCH: 136, train_loss: 5.052333491189139
EPOCH: 136, valid_loss: 5.046961511884417
EPOCH: 137, train_loss: 5.051977498190744
EPOCH: 137, valid_loss: 5.026585442679269
EPOCH: 138, train_loss: 5.051280566624233
EPOCH: 138, valid_loss: 5.024356126785278
EPOCH: 139, train_loss: 5.0420868737357
EPOCH: 139, valid_loss: 5.026165996279035
EPOCH: 140, train_loss: 5.052245821271624
EPOCH: 140, valid_loss: 5.036426135471889
EPOCH: 141, train_loss: 5.039925643375942
EPOCH: 141, valid_loss: 5.0399355207170755
EPOCH: 142, train_loss: 5.06016595023019
EPOCH: 142, valid_loss: 5.009778669902256
EPOCH: 143, train_loss: 5.027878556932722
EPOCH: 143, valid_loss: 5.026627506528582
EPOCH: 144, train_loss: 5.045112677982876
EPOCH: 144, valid_loss: 5.025803429739816
EPOCH: 145, train_loss: 5.049749987465995
EPOCH: 145, valid_loss: 4.991468293326242
EPOCH: 146, train_loss: 5.039685521806989
EPOCH: 146, valid_loss: 5.005275998796735
EPOCH: 147, train_loss: 5.0414566312517435
EPOCH: 147, valid_loss: 5.0090367794036865
EPOCH: 148, train_loss: 5.060154097420829
EPOCH: 148, valid_loss: 5.010376964296613
EPOCH: 149, train_loss: 5.028685092926025
EPOCH: 149, valid_loss: 5.017073937824795
EPOCH: 150, train_loss: 5.021196774074009
EPOCH: 150, valid_loss: 5.00727493422372
EPOCH: 151, train_loss: 5.023523875645229
EPOCH: 151, valid_loss: 5.029957430703299
EPOCH: 152, train_loss: 5.025380747658866
EPOCH: 152, valid_loss: 5.011909893580845
EPOCH: 153, train_loss: 5.034622941698347
EPOCH: 153, valid_loss: 5.025402784347534
EPOCH: 154, train_loss: 5.028689997536795
EPOCH: 154, valid_loss: 5.039455209459577
EPOCH: 155, train_loss: 5.056427546909878
EPOCH: 155, valid_loss: 5.037562710898263
EPOCH: 156, train_loss: 5.028338500431606
EPOCH: 156, valid_loss: 5.020458221435547
EPOCH: 157, train_loss: 5.029223714556013
EPOCH: 157, valid_loss: 5.0110039710998535
EPOCH: 158, train_loss: 5.04022605078561
EPOCH: 158, valid_loss: 5.015240873609271
EPOCH: 159, train_loss: 5.017907960074289
EPOCH: 159, valid_loss: 5.008644104003906
EPOCH: 160, train_loss: 5.040510790688651
EPOCH: 160, valid_loss: 5.018366643360683
EPOCH: 161, train_loss: 5.041761602674212
EPOCH: 161, valid_loss: 5.006035089492798
EPOCH: 162, train_loss: 5.0081859316144675
EPOCH: 162, valid_loss: 4.980419874191284
EPOCH: 163, train_loss: 5.016016483306885
EPOCH: 163, valid_loss: 4.9827026299067905
EPOCH: 164, train_loss: 5.009188311440604
EPOCH: 164, valid_loss: 4.968596867152622
EPOCH: 165, train_loss: 5.025250979832241
EPOCH: 165, valid_loss: 4.973089422498431
EPOCH: 166, train_loss: 5.004811082567487
EPOCH: 166, valid_loss: 4.974753652300153
EPOCH: 167, train_loss: 5.060367175510952
EPOCH: 167, valid_loss: 4.977691684450422
EPOCH: 168, train_loss: 5.028844356536865
EPOCH: 168, valid_loss: 4.976636171340942
EPOCH: 169, train_loss: 5.023079122815814
EPOCH: 169, valid_loss: 4.985960960388184
EPOCH: 170, train_loss: 4.998977048056466
EPOCH: 170, valid_loss: 4.990676403045654
EPOCH: 171, train_loss: 5.019383839198521
EPOCH: 171, valid_loss: 4.978845494134085
EPOCH: 172, train_loss: 5.012604100363595
EPOCH: 172, valid_loss: 4.987817049026489
EPOCH: 173, train_loss: 4.997799055916922
EPOCH: 173, valid_loss: 4.992893150874546
EPOCH: 174, train_loss: 4.980059828077044
EPOCH: 174, valid_loss: 4.974001373563494
EPOCH: 175, train_loss: 4.993728876113892
EPOCH: 175, valid_loss: 4.985541650227138
EPOCH: 176, train_loss: 5.007039478846958
EPOCH: 176, valid_loss: 4.981685229710171
EPOCH: 177, train_loss: 5.016452039991107
EPOCH: 177, valid_loss: 4.98960736819676
EPOCH: 178, train_loss: 5.02237285886492
EPOCH: 178, valid_loss: 4.975116491317749
EPOCH: 179, train_loss: 5.012644699641636
EPOCH: 179, valid_loss: 4.977704797472272
EPOCH: 180, train_loss: 5.014478819710868
EPOCH: 180, valid_loss: 4.973869868687221
EPOCH: 181, train_loss: 4.986585412706647
EPOCH: 181, valid_loss: 4.979766062327793
EPOCH: 182, train_loss: 5.016477039882115
EPOCH: 182, valid_loss: 4.982498713902065
EPOCH: 183, train_loss: 5.010665621076312
EPOCH: 183, valid_loss: 4.97085097857884
EPOCH: 184, train_loss: 4.995532376425607
EPOCH: 184, valid_loss: 4.9754180908203125
EPOCH: 185, train_loss: 4.997999055044992
EPOCH: 185, valid_loss: 4.965517146246774
EPOCH: 186, train_loss: 4.99087279183524
EPOCH: 186, valid_loss: 4.969098363603864
EPOCH: 187, train_loss: 5.025347028459821
EPOCH: 187, valid_loss: 4.982921464102609
EPOCH: 188, train_loss: 5.001165866851807
EPOCH: 188, valid_loss: 4.9600231647491455
EPOCH: 189, train_loss: 5.031137875148228
EPOCH: 189, valid_loss: 4.962597574506487
EPOCH: 190, train_loss: 4.988119465964181
EPOCH: 190, valid_loss: 4.97492858341762
EPOCH: 191, train_loss: 4.988527297973633
EPOCH: 191, valid_loss: 4.975343567984445
EPOCH: 192, train_loss: 4.983313696725028
EPOCH: 192, valid_loss: 4.977651766368321
EPOCH: 193, train_loss: 4.995125770568848
EPOCH: 193, valid_loss: 4.985265357153756
EPOCH: 194, train_loss: 5.01237644468035
EPOCH: 194, valid_loss: 5.031088045665196
EPOCH: 195, train_loss: 4.983242886407035
EPOCH: 195, valid_loss: 4.994385174342564
EPOCH: 196, train_loss: 4.986518859863281
EPOCH: 196, valid_loss: 5.01075622013637
EPOCH: 197, train_loss: 4.995626177106585
EPOCH: 197, valid_loss: 5.010066747665405
EPOCH: 198, train_loss: 4.95916713987078
EPOCH: 198, valid_loss: 5.0134349550519675
EPOCH: 199, train_loss: 4.965867349079677
EPOCH: 199, valid_loss: 5.011393955775669
EPOCH: 200, train_loss: 4.988789013453892
EPOCH: 200, valid_loss: 4.980365344456264
EPOCH: 201, train_loss: 4.992370877947126
EPOCH: 201, valid_loss: 4.957474504198347
EPOCH: 202, train_loss: 5.011529105050223
EPOCH: 202, valid_loss: 4.984068529946463
EPOCH: 203, train_loss: 4.972107819148472
EPOCH: 203, valid_loss: 4.960992336273193
EPOCH: 204, train_loss: 4.997303519930158
EPOCH: 204, valid_loss: 4.966567754745483
EPOCH: 205, train_loss: 4.9589056628091
EPOCH: 205, valid_loss: 4.961809294564383
EPOCH: 206, train_loss: 4.971253088542393
EPOCH: 206, valid_loss: 4.965398584093366
EPOCH: 207, train_loss: 4.993893418993268
EPOCH: 207, valid_loss: 4.954350335257394
EPOCH: 208, train_loss: 4.9748625074114114
EPOCH: 208, valid_loss: 4.951195819037301
EPOCH: 209, train_loss: 5.017685004643032
EPOCH: 209, valid_loss: 4.976439816611154
EPOCH: 210, train_loss: 4.98484434400286
EPOCH: 210, valid_loss: 4.982947622026716
EPOCH: 211, train_loss: 4.993622098650251
EPOCH: 211, valid_loss: 5.030735833304269
EPOCH: 212, train_loss: 4.965434721537998
EPOCH: 212, valid_loss: 4.985772405351911
EPOCH: 213, train_loss: 4.983485085623605
EPOCH: 213, valid_loss: 4.981866189411709
EPOCH: 214, train_loss: 4.973759208406721
EPOCH: 214, valid_loss: 4.984756571905954
EPOCH: 215, train_loss: 4.994112082890102
EPOCH: 215, valid_loss: 5.01522295815604
EPOCH: 216, train_loss: 4.949315105165754
EPOCH: 216, valid_loss: 4.987686361585345
EPOCH: 217, train_loss: 4.945194210324969
EPOCH: 217, valid_loss: 4.993391650063651
EPOCH: 218, train_loss: 4.947375774383545
EPOCH: 218, valid_loss: 5.010406221662249
EPOCH: 219, train_loss: 4.958355120250157
EPOCH: 219, valid_loss: 5.023835318429129
EPOCH: 220, train_loss: 4.951501131057739
EPOCH: 220, valid_loss: 4.983709812164307
EPOCH: 221, train_loss: 4.959641592843192
EPOCH: 221, valid_loss: 4.978663989475796
EPOCH: 222, train_loss: 4.958637782505581
EPOCH: 222, valid_loss: 5.004777090890067
EPOCH: 223, train_loss: 4.965552943093436
EPOCH: 223, valid_loss: 4.995959077562604
EPOCH: 224, train_loss: 5.00495593888419
EPOCH: 224, valid_loss: 4.993876423154559
EPOCH: 225, train_loss: 4.986665453229632
EPOCH: 225, valid_loss: 4.966344492776053
EPOCH: 226, train_loss: 4.981514624186924
EPOCH: 226, valid_loss: 4.97935278075082
EPOCH: 227, train_loss: 4.947187219347272
EPOCH: 227, valid_loss: 4.955109664372036
EPOCH: 228, train_loss: 4.970664024353027
EPOCH: 228, valid_loss: 4.960790157318115
EPOCH: 229, train_loss: 4.9607721737452914
EPOCH: 229, valid_loss: 4.970941066741943
EPOCH: 230, train_loss: 4.955499342509678
EPOCH: 230, valid_loss: 5.003983701978411
EPOCH: 231, train_loss: 4.965086017336164
EPOCH: 231, valid_loss: 5.056940487452915
EPOCH: 232, train_loss: 4.957043818065098
EPOCH: 232, valid_loss: 5.012765066964286
EPOCH: 233, train_loss: 5.006271975381034
EPOCH: 233, valid_loss: 5.005254949842181
EPOCH: 234, train_loss: 4.950172185897827
EPOCH: 234, valid_loss: 5.00920557975769
EPOCH: 235, train_loss: 4.953368663787842
EPOCH: 235, valid_loss: 4.99046972819737
EPOCH: 236, train_loss: 4.935867650168283
EPOCH: 236, valid_loss: 4.979193823678153
EPOCH: 237, train_loss: 4.945127078465053
EPOCH: 237, valid_loss: 4.9939426353999545
EPOCH: 238, train_loss: 4.953882898603167
EPOCH: 238, valid_loss: 5.027245317186628
EPOCH: 239, train_loss: 4.9671197278159
EPOCH: 239, valid_loss: 4.9831851209912985
EPOCH: 240, train_loss: 4.926831177302769
EPOCH: 240, valid_loss: 4.973565442221505
EPOCH: 241, train_loss: 5.003644193921771
EPOCH: 241, valid_loss: 5.016473633902414

# Inference

## Create dataset for test

In [40]:
# ====================================================
# Dataset for test
# ====================================================

mean = np.array([0.37087523, 0.370876, 0.3708759] )
std = np.array([0.21022698, 0.21022713, 0.21022706])

class IWildcamTestDataset(Dataset):
    def __init__(self, df, tfms=None):
        self.ids = df["id"]
        self.idx = df["idx"]
        self.tfms = tfms
        
    def __len__(self):
        return len(self.ids)
    
    def __getitem__(self, idx):
        size = (256, 256)
        image_id = self.ids[idx]
        image_idx = self.idx[idx]
        
        image_path = TEST_CROPED_DATA + f"{image_id}_{image_idx}.jpg"
        
        img = cv2.resize(cv2.cvtColor(cv2.imread(image_path), cv2.COLOR_BGR2RGB),size)

        if self.tfms is not None:
            augmented = self.tfms(image=img)
            img = augmented['image']
            
        # we should normalize here
        return img2tensor((img/255.0 - mean)/std), image_id

In [41]:
ds_test = IWildcamTestDataset(df_croped_img_ids_test)
dl_test = DataLoader(ds_test,batch_size=32,shuffle=False,num_workers=NUM_WORKERS)

## Load trained model

In [42]:
model = enet_v2(backbone="tf_efficientnet_b0", out_dim=205)
model.to(DEVICE)
model.load_state_dict(torch.load(f"{epoch+1}_.pth"))
model.eval()

enet_v2(
  (enet): EfficientNet(
    (conv_stem): Conv2dSame(3, 32, kernel_size=(3, 3), stride=(2, 2), bias=False)
    (bn1): BatchNorm2d(32, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
    (act1): SwishMe()
    (blocks): Sequential(
      (0): Sequential(
        (0): DepthwiseSeparableConv(
          (conv_dw): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32, bias=False)
          (bn1): BatchNorm2d(32, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(32, 8, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(8, 32, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pw): Conv2d(32, 16, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn2): BatchNorm2d(16, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): Identity()
        )
      )
      (1): Sequential(
        (0): InvertedResidual(
          (conv_pw): Conv2d(16, 96, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(96, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2dSame(96, 96, kernel_size=(3, 3), stride=(2, 2), groups=96, bias=False)
          (bn2): BatchNorm2d(96, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(96, 4, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(4, 96, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(96, 24, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(24, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (1): InvertedResidual(
          (conv_pw): Conv2d(24, 144, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(144, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2d(144, 144, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=144, bias=False)
          (bn2): BatchNorm2d(144, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(144, 6, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(6, 144, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(144, 24, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(24, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (2): Sequential(
        (0): InvertedResidual(
          (conv_pw): Conv2d(24, 144, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(144, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2dSame(144, 144, kernel_size=(5, 5), stride=(2, 2), groups=144, bias=False)
          (bn2): BatchNorm2d(144, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(144, 6, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(6, 144, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(144, 40, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(40, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (1): InvertedResidual(
          (conv_pw): Conv2d(40, 240, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(240, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2d(240, 240, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=240, bias=False)
          (bn2): BatchNorm2d(240, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(240, 10, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(10, 240, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(240, 40, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(40, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (3): Sequential(
        (0): InvertedResidual(
          (conv_pw): Conv2d(40, 240, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(240, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2dSame(240, 240, kernel_size=(3, 3), stride=(2, 2), groups=240, bias=False)
          (bn2): BatchNorm2d(240, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(240, 10, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(10, 240, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(240, 80, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(80, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (1): InvertedResidual(
          (conv_pw): Conv2d(80, 480, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(480, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2d(480, 480, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=480, bias=False)
          (bn2): BatchNorm2d(480, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(480, 20, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(20, 480, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(480, 80, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(80, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (2): InvertedResidual(
          (conv_pw): Conv2d(80, 480, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(480, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2d(480, 480, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=480, bias=False)
          (bn2): BatchNorm2d(480, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(480, 20, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(20, 480, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(480, 80, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(80, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (4): Sequential(
        (0): InvertedResidual(
          (conv_pw): Conv2d(80, 480, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(480, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2d(480, 480, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=480, bias=False)
          (bn2): BatchNorm2d(480, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(480, 20, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(20, 480, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(480, 112, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(112, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (1): InvertedResidual(
          (conv_pw): Conv2d(112, 672, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(672, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2d(672, 672, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=672, bias=False)
          (bn2): BatchNorm2d(672, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(672, 28, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(28, 672, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(672, 112, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(112, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (2): InvertedResidual(
          (conv_pw): Conv2d(112, 672, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(672, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2d(672, 672, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=672, bias=False)
          (bn2): BatchNorm2d(672, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(672, 28, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(28, 672, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(672, 112, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(112, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (5): Sequential(
        (0): InvertedResidual(
          (conv_pw): Conv2d(112, 672, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(672, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2dSame(672, 672, kernel_size=(5, 5), stride=(2, 2), groups=672, bias=False)
          (bn2): BatchNorm2d(672, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(672, 28, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(28, 672, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(672, 192, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(192, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (1): InvertedResidual(
          (conv_pw): Conv2d(192, 1152, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(1152, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2d(1152, 1152, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=1152, bias=False)
          (bn2): BatchNorm2d(1152, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(1152, 48, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(48, 1152, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(1152, 192, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(192, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (2): InvertedResidual(
          (conv_pw): Conv2d(192, 1152, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(1152, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2d(1152, 1152, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=1152, bias=False)
          (bn2): BatchNorm2d(1152, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(1152, 48, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(48, 1152, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(1152, 192, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(192, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
        (3): InvertedResidual(
          (conv_pw): Conv2d(192, 1152, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(1152, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2d(1152, 1152, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=1152, bias=False)
          (bn2): BatchNorm2d(1152, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(1152, 48, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(48, 1152, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(1152, 192, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(192, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (6): Sequential(
        (0): InvertedResidual(
          (conv_pw): Conv2d(192, 1152, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(1152, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act1): SwishMe()
          (conv_dw): Conv2d(1152, 1152, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=1152, bias=False)
          (bn2): BatchNorm2d(1152, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
          (act2): SwishMe()
          (se): SqueezeExcite(
            (conv_reduce): Conv2d(1152, 48, kernel_size=(1, 1), stride=(1, 1))
            (act1): SwishMe()
            (conv_expand): Conv2d(48, 1152, kernel_size=(1, 1), stride=(1, 1))
          )
          (conv_pwl): Conv2d(1152, 320, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(320, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
    )
    (conv_head): Conv2d(320, 1280, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (bn2): BatchNorm2d(1280, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
    (act2): SwishMe()
    (global_pool): SelectAdaptivePool2d (pool_type=avg, flatten=True)
    (classifier): Identity()
  )
  (myfc): Linear(in_features=1280, out_features=205, bias=True)
)

In [43]:
pred_categories = []
pred_img_ids = []

## inference

In [44]:
with torch.no_grad():
    for imgs, img_ids in tqdm(dl_test):
        imgs = imgs.to(DEVICE)
        
        outputs = model(imgs)
        output_labels = torch.argmax(outputs, dim=1).tolist()
        pred_categories += output_labels
        pred_img_ids += img_ids

  0%|          | 0/1008 [00:00<?, ?it/s]

In [45]:
pred = collections.defaultdict(list)
for category, img_id in zip(pred_categories, pred_img_ids):
    pred[img_id].append(category)

In [46]:
pred

defaultdict(list,
            {'915879a0-21bc-11ea-a13a-137349068a90': [82],
             '91588116-21bc-11ea-a13a-137349068a90': [72],
             '9158a2f4-21bc-11ea-a13a-137349068a90': [172],
             '9158aaa6-21bc-11ea-a13a-137349068a90': [39],
             '9158f1a0-21bc-11ea-a13a-137349068a90': [49],
             '9159244a-21bc-11ea-a13a-137349068a90': [167],
             '91599f88-21bc-11ea-a13a-137349068a90': [119],
             '915a05ea-21bc-11ea-a13a-137349068a90': [119],
             '915a0cde-21bc-11ea-a13a-137349068a90': [104,
              173,
              183,
              183,
              125,
              104],
             '915a41b8-21bc-11ea-a13a-137349068a90': [61, 65, 61],
             '915a9f14-21bc-11ea-a13a-137349068a90': [66],
             '915aa658-21bc-11ea-a13a-137349068a90': [70],
             '915ad13c-21bc-11ea-a13a-137349068a90': [39],
             '915ad448-21bc-11ea-a13a-137349068a90': [36],
             '915b3d3e-21bc-11ea-a13a-137349068a90': [130, 94],
             '915b5d14-21bc-11ea-a13a-137349068a90': [198],
             '915b765a-21bc-11ea-a13a-137349068a90': [172],
             '915b826c-21bc-11ea-a13a-137349068a90': [41],
             '915bc998-21bc-11ea-a13a-137349068a90': [173],
             '915be07c-21bc-11ea-a13a-137349068a90': [198],
             '915c31bc-21bc-11ea-a13a-137349068a90': [172],
             '915c6614-21bc-11ea-a13a-137349068a90': [93],
             '915c723a-21bc-11ea-a13a-137349068a90': [112],
             '915c7532-21bc-11ea-a13a-137349068a90': [175],
             '915c8824-21bc-11ea-a13a-137349068a90': [112],
             '915c9f94-21bc-11ea-a13a-137349068a90': [116],
             '915cc442-21bc-11ea-a13a-137349068a90': [166],
             '915d7022-21bc-11ea-a13a-137349068a90': [80],
             '915d732e-21bc-11ea-a13a-137349068a90': [116, 87, 203],
             '915db398-21bc-11ea-a13a-137349068a90': [172],
             '915dc5cc-21bc-11ea-a13a-137349068a90': [34],
             '915e102c-21bc-11ea-a13a-137349068a90': [183],
             '915e4862-21bc-11ea-a13a-137349068a90': [51],
             '915e57b2-21bc-11ea-a13a-137349068a90': [65],
             '915e6158-21bc-11ea-a13a-137349068a90': [117],
             '915ec918-21bc-11ea-a13a-137349068a90': [116],
             '915f2d2c-21bc-11ea-a13a-137349068a90': [82],
             '915f375e-21bc-11ea-a13a-137349068a90': [64],
             '915f76a6-21bc-11ea-a13a-137349068a90': [49, 41, 69],
             '915facde-21bc-11ea-a13a-137349068a90': [67, 36],
             '915fc188-21bc-11ea-a13a-137349068a90': [98],
             '915fd9d4-21bc-11ea-a13a-137349068a90': [119],
             '915fffcc-21bc-11ea-a13a-137349068a90': [82],
             '916020c4-21bc-11ea-a13a-137349068a90': [80],
             '91608fb4-21bc-11ea-a13a-137349068a90': [82],
             '9160adfa-21bc-11ea-a13a-137349068a90': [64],
             '9160dbe0-21bc-11ea-a13a-137349068a90': [80],
             '9160e5ea-21bc-11ea-a13a-137349068a90': [110],
             '9160fe86-21bc-11ea-a13a-137349068a90': [202],
             '91611d26-21bc-11ea-a13a-137349068a90': [171],
             '9161913e-21bc-11ea-a13a-137349068a90': [130, 93, 119, 119],
             '9161b40c-21bc-11ea-a13a-137349068a90': [130],
             '9161b79a-21bc-11ea-a13a-137349068a90': [200],
             '9161d18a-21bc-11ea-a13a-137349068a90': [67, 50],
             '91623be8-21bc-11ea-a13a-137349068a90': [97],
             '916249bc-21bc-11ea-a13a-137349068a90': [82],
             '91626316-21bc-11ea-a13a-137349068a90': [129, 63, 127],
             '9162782e-21bc-11ea-a13a-137349068a90': [113],
             '9162ba50-21bc-11ea-a13a-137349068a90': [1],
             '9162c0c2-21bc-11ea-a13a-137349068a90': [175],
             '9162fd94-21bc-11ea-a13a-137349068a90': [80],
             '91639650-21bc-11ea-a13a-137349068a90': [80],
             '9163ab04-21bc-11ea-a13a-137349068a90': [165],
             '9163bed2-21bc-11ea-a13a-137349068a90': [196],
             '9163f186-21bc-11ea-a13a-137349068a90': [84],
             '91640306-21bc-11ea-a13a-137349068a90': [178],
             '91641e68-21bc-11ea-a13a-137349068a90': [172],
             '91645748-21bc-11ea-a13a-137349068a90': [80],
             '9164ac84-21bc-11ea-a13a-137349068a90': [166],
             '9164d060-21bc-11ea-a13a-137349068a90': [72],
             '9164e3ac-21bc-11ea-a13a-137349068a90': [122],
             '91652416-21bc-11ea-a13a-137349068a90': [113, 82],
             '91654388-21bc-11ea-a13a-137349068a90': [67],
             '916553dc-21bc-11ea-a13a-137349068a90': [107, 166],
             '916578a8-21bc-11ea-a13a-137349068a90': [89],
             '9165ae90-21bc-11ea-a13a-137349068a90': [114],
             '91664634-21bc-11ea-a13a-137349068a90': [89],
             '91665ac0-21bc-11ea-a13a-137349068a90': [190],
             '91665ebc-21bc-11ea-a13a-137349068a90': [50, 50],
             '9166820c-21bc-11ea-a13a-137349068a90': [122, 10],
             '9166f796-21bc-11ea-a13a-137349068a90': [60],
             '916714ce-21bc-11ea-a13a-137349068a90': [38],
             '916741ce-21bc-11ea-a13a-137349068a90': [178],
             '9167a5f6-21bc-11ea-a13a-137349068a90': [80],
             '9167b154-21bc-11ea-a13a-137349068a90': [69],
             '9167d238-21bc-11ea-a13a-137349068a90': [172],
             '9167e00c-21bc-11ea-a13a-137349068a90': [119],
             '91685762-21bc-11ea-a13a-137349068a90': [80],
             '91686338-21bc-11ea-a13a-137349068a90': [54],
             '9168a91a-21bc-11ea-a13a-137349068a90': [82],
             '9168d9f8-21bc-11ea-a13a-137349068a90': [139, 32],
             '9168ff46-21bc-11ea-a13a-137349068a90': [168],
             '91691508-21bc-11ea-a13a-137349068a90': [87],
             '9169626a-21bc-11ea-a13a-137349068a90': [51, 73],
             '9169a0e0-21bc-11ea-a13a-137349068a90': [172],
             '9169b864-21bc-11ea-a13a-137349068a90': [82, 179],
             '916a0512-21bc-11ea-a13a-137349068a90': [82],
             '916a1b10-21bc-11ea-a13a-137349068a90': [82],
             '916a4004-21bc-11ea-a13a-137349068a90': [167],
             '916aa918-21bc-11ea-a13a-137349068a90': [34],
             '916aace2-21bc-11ea-a13a-137349068a90': [129],
             '916ac038-21bc-11ea-a13a-137349068a90': [69],
             '916aeaf4-21bc-11ea-a13a-137349068a90': [197, 93, 117, 93, 82],
             '916b107e-21bc-11ea-a13a-137349068a90': [106],
             '916b1fba-21bc-11ea-a13a-137349068a90': [122, 10],
             '916b7a14-21bc-11ea-a13a-137349068a90': [80],
             '916baf84-21bc-11ea-a13a-137349068a90': [109],
             '916bb38a-21bc-11ea-a13a-137349068a90': [167],
             '916bd888-21bc-11ea-a13a-137349068a90': [72],
             '916bfb4c-21bc-11ea-a13a-137349068a90': [97],
             '916bff2a-21bc-11ea-a13a-137349068a90': [119],
             '916c2a0e-21bc-11ea-a13a-137349068a90': [112],
             '916ccca2-21bc-11ea-a13a-137349068a90': [82],
             '916d062c-21bc-11ea-a13a-137349068a90': [154, 1],
             '916d62a2-21bc-11ea-a13a-137349068a90': [97, 1, 35, 39, 112, 82],
             '916d68c4-21bc-11ea-a13a-137349068a90': [130],
             '916d91fa-21bc-11ea-a13a-137349068a90': [97],
             '916df71c-21bc-11ea-a13a-137349068a90': [130],
             '916e73d6-21bc-11ea-a13a-137349068a90': [112],
             '916e9d66-21bc-11ea-a13a-137349068a90': [80],
             '916ea11c-21bc-11ea-a13a-137349068a90': [90],
             '916ebc56-21bc-11ea-a13a-137349068a90': [112],
             '916ec7c8-21bc-11ea-a13a-137349068a90': [110],
             '916f0ab2-21bc-11ea-a13a-137349068a90': [54],
             '916f3834-21bc-11ea-a13a-137349068a90': [104],
             '916fcec0-21bc-11ea-a13a-137349068a90': [82],
             '916ff8f0-21bc-11ea-a13a-137349068a90': [172],
             '91706fc4-21bc-11ea-a13a-137349068a90': [159, 93, 60],
             '9170a9c6-21bc-11ea-a13a-137349068a90': [82],
             '9170b132-21bc-11ea-a13a-137349068a90': [165],
             '9170c424-21bc-11ea-a13a-137349068a90': [119],
             '9170d464-21bc-11ea-a13a-137349068a90': [122],
             '9170f32c-21bc-11ea-a13a-137349068a90': [197, 82],
             '9171147e-21bc-11ea-a13a-137349068a90': [69],
             '91711834-21bc-11ea-a13a-137349068a90': [112],
             '91716190-21bc-11ea-a13a-137349068a90': [166],
             '9172463c-21bc-11ea-a13a-137349068a90': [105],
             '91727b8e-21bc-11ea-a13a-137349068a90': [82],
             '917282e6-21bc-11ea-a13a-137349068a90': [130],
             '9172ec54-21bc-11ea-a13a-137349068a90': [112],
             '91735806-21bc-11ea-a13a-137349068a90': [60, 166],
             '917380a6-21bc-11ea-a13a-137349068a90': [116],
             '91738a24-21bc-11ea-a13a-137349068a90': [10, 71],
             '9173941a-21bc-11ea-a13a-137349068a90': [91],
             '9173c3ae-21bc-11ea-a13a-137349068a90': [51],
             '9173d7c2-21bc-11ea-a13a-137349068a90': [72],
             '9174204c-21bc-11ea-a13a-137349068a90': [110, 190, 117, 93],
             '917451a2-21bc-11ea-a13a-137349068a90': [112],
             '9174deb0-21bc-11ea-a13a-137349068a90': [119],
             '9174e1bc-21bc-11ea-a13a-137349068a90': [172],
             '9174eb1c-21bc-11ea-a13a-137349068a90': [113],
             '9174f1d4-21bc-11ea-a13a-137349068a90': [82],
             '91756614-21bc-11ea-a13a-137349068a90': [202],
             '91757bc2-21bc-11ea-a13a-137349068a90': [129],
             '91758e00-21bc-11ea-a13a-137349068a90': [72],
             '917590ee-21bc-11ea-a13a-137349068a90': [113],
             '917607cc-21bc-11ea-a13a-137349068a90': [34],
             '91762644-21bc-11ea-a13a-137349068a90': [112],
             '917631d4-21bc-11ea-a13a-137349068a90': [139],
             '91764bb0-21bc-11ea-a13a-137349068a90': [176, 69, 63, 39],
             '917661d6-21bc-11ea-a13a-137349068a90': [82],
             '917668d4-21bc-11ea-a13a-137349068a90': [130, 93],
             '91767388-21bc-11ea-a13a-137349068a90': [80],
             '9176775c-21bc-11ea-a13a-137349068a90': [82, 80, 106],
             '9176ec28-21bc-11ea-a13a-137349068a90': [113, 166],
             '917715e0-21bc-11ea-a13a-137349068a90': [82],
             '91775b5e-21bc-11ea-a13a-137349068a90': [6],
             '9177a8a2-21bc-11ea-a13a-137349068a90': [82],
             '9177be5a-21bc-11ea-a13a-137349068a90': [72],
             '9177e1aa-21bc-11ea-a13a-137349068a90': [200],
             '9177e6fa-21bc-11ea-a13a-137349068a90': [97],
             '91781b66-21bc-11ea-a13a-137349068a90': [93],
             '91783560-21bc-11ea-a13a-137349068a90': [166],
             '91783c86-21bc-11ea-a13a-137349068a90': [167],
             '91787fb6-21bc-11ea-a13a-137349068a90': [127, 68],
             '9178d952-21bc-11ea-a13a-137349068a90': [15],
             '91792e66-21bc-11ea-a13a-137349068a90': [39],
             '91794036-21bc-11ea-a13a-137349068a90': [58],
             '9179470c-21bc-11ea-a13a-137349068a90': [93, 168],
             '91797916-21bc-11ea-a13a-137349068a90': [112],
             '917997d4-21bc-11ea-a13a-137349068a90': [93],
             '9179a472-21bc-11ea-a13a-137349068a90': [102],
             '9179e7fc-21bc-11ea-a13a-137349068a90': [39],
             '9179fa26-21bc-11ea-a13a-137349068a90': [172],
             '917a63bc-21bc-11ea-a13a-137349068a90': [122, 15],
             '917a69ca-21bc-11ea-a13a-137349068a90': [64],
             '917a7046-21bc-11ea-a13a-137349068a90': [49],
             '917ad75c-21bc-11ea-a13a-137349068a90': [65, 72],
             '917aee2c-21bc-11ea-a13a-137349068a90': [72],
             '917b547a-21bc-11ea-a13a-137349068a90': [172, 32],
             '917ba9a2-21bc-11ea-a13a-137349068a90': [112],
             '917c30de-21bc-11ea-a13a-137349068a90': [196],
             '917c83ea-21bc-11ea-a13a-137349068a90': [112],
             '917cc896-21bc-11ea-a13a-137349068a90': [82],
             '917d0ffe-21bc-11ea-a13a-137349068a90': [175, 110],
             '917d18f0-21bc-11ea-a13a-137349068a90': [29],
             '917d522a-21bc-11ea-a13a-137349068a90': [1, 188],
             '917d5b80-21bc-11ea-a13a-137349068a90': [35, 39, 127, 165],
             '917d886c-21bc-11ea-a13a-137349068a90': [73],
             '917dacd4-21bc-11ea-a13a-137349068a90': [73],
             '917df194-21bc-11ea-a13a-137349068a90': [29],
             '917e1836-21bc-11ea-a13a-137349068a90': [113, 169, 197],
             '917e1b88-21bc-11ea-a13a-137349068a90': [49],
             '917e2fc4-21bc-11ea-a13a-137349068a90': [69],
             '917ecb14-21bc-11ea-a13a-137349068a90': [130],
             '917ece02-21bc-11ea-a13a-137349068a90': [56],
             '917ed104-21bc-11ea-a13a-137349068a90': [57],
             '917f1f88-21bc-11ea-a13a-137349068a90': [82],
             '917f4cec-21bc-11ea-a13a-137349068a90': [72],
             '917f5746-21bc-11ea-a13a-137349068a90': [72],
             '917f792e-21bc-11ea-a13a-137349068a90': [105],
             '917fc320-21bc-11ea-a13a-137349068a90': [167],
             '917fd5cc-21bc-11ea-a13a-137349068a90': [73],
             '91803896-21bc-11ea-a13a-137349068a90': [126],
             '91806c3a-21bc-11ea-a13a-137349068a90': [167, 167],
             '9180a1b4-21bc-11ea-a13a-137349068a90': [167],
             '9180bb86-21bc-11ea-a13a-137349068a90': [175],
             '9180caf4-21bc-11ea-a13a-137349068a90': [131],
             '9181375a-21bc-11ea-a13a-137349068a90': [176],
             '918155fa-21bc-11ea-a13a-137349068a90': [61, 104, 104],
             '918165a4-21bc-11ea-a13a-137349068a90': [119],
             '91819a60-21bc-11ea-a13a-137349068a90': [36],
             '9181a55a-21bc-11ea-a13a-137349068a90': [139],
             '9181fd02-21bc-11ea-a13a-137349068a90': [104],
             '918222dc-21bc-11ea-a13a-137349068a90': [64, 199],
             '91822eb2-21bc-11ea-a13a-137349068a90': [67],
             '91827e94-21bc-11ea-a13a-137349068a90': [117],
             '918304f4-21bc-11ea-a13a-137349068a90': [97],
             '9183932e-21bc-11ea-a13a-137349068a90': [80],
             '9183c114-21bc-11ea-a13a-137349068a90': [107],
             '9183ea9a-21bc-11ea-a13a-137349068a90': [104],
             '9183ecb6-21bc-11ea-a13a-137349068a90': [199],
             '91840642-21bc-11ea-a13a-137349068a90': [69],
             '9184408a-21bc-11ea-a13a-137349068a90': [82],
             '918459a8-21bc-11ea-a13a-137349068a90': [51],
             '91849094-21bc-11ea-a13a-137349068a90': [133],
             '9184adea-21bc-11ea-a13a-137349068a90': [80],
             '9184b114-21bc-11ea-a13a-137349068a90': [119],
             '9184c6f4-21bc-11ea-a13a-137349068a90': [23],
             '918518f2-21bc-11ea-a13a-137349068a90': [113],
             '91851c62-21bc-11ea-a13a-137349068a90': [127],
             '91853990-21bc-11ea-a13a-137349068a90': [80],
             '91857054-21bc-11ea-a13a-137349068a90': [93],
             '9185810c-21bc-11ea-a13a-137349068a90': [41],
             '9185b88e-21bc-11ea-a13a-137349068a90': [93],
             '9185e12e-21bc-11ea-a13a-137349068a90': [130],
             '91864c7c-21bc-11ea-a13a-137349068a90': [119],
             '91868c28-21bc-11ea-a13a-137349068a90': [83, 64, 83],
             '9186cac6-21bc-11ea-a13a-137349068a90': [166],
             '9186df2a-21bc-11ea-a13a-137349068a90': [80],
             '9187ad1a-21bc-11ea-a13a-137349068a90': [87],
             '9187c5fc-21bc-11ea-a13a-137349068a90': [119],
             '9187e9ec-21bc-11ea-a13a-137349068a90': [132],
             '9187fc34-21bc-11ea-a13a-137349068a90': [172],
             '91880d82-21bc-11ea-a13a-137349068a90': [36, 67],
             '918817be-21bc-11ea-a13a-137349068a90': [63, 35],
             '918821dc-21bc-11ea-a13a-137349068a90': [39],
             '91889f40-21bc-11ea-a13a-137349068a90': [69],
             '9188da78-21bc-11ea-a13a-137349068a90': [51],
             '918985b8-21bc-11ea-a13a-137349068a90': [130, 93],
             '9189c8d4-21bc-11ea-a13a-137349068a90': [67],
             '918a1cf8-21bc-11ea-a13a-137349068a90': [94, 82, 130],
             '918a2c0c-21bc-11ea-a13a-137349068a90': [97],
             '918a3332-21bc-11ea-a13a-137349068a90': [80],
             '918acd88-21bc-11ea-a13a-137349068a90': [166],
             '918ad864-21bc-11ea-a13a-137349068a90': [69],
             '918ae818-21bc-11ea-a13a-137349068a90': [93],
             '918b16da-21bc-11ea-a13a-137349068a90': [198],
             '918b1de2-21bc-11ea-a13a-137349068a90': [121, 179],
             '918b3b74-21bc-11ea-a13a-137349068a90': [46],
             '918bbaa4-21bc-11ea-a13a-137349068a90': [165],
             '918bc1a2-21bc-11ea-a13a-137349068a90': [172],
             '918c032e-21bc-11ea-a13a-137349068a90': [41],
             '918c151c-21bc-11ea-a13a-137349068a90': [82],
             '918c7106-21bc-11ea-a13a-137349068a90': [122],
             '918c93c0-21bc-11ea-a13a-137349068a90': [97],
             '918ca6a8-21bc-11ea-a13a-137349068a90': [117],
             '918cc7a0-21bc-11ea-a13a-137349068a90': [113],
             '918cfeaa-21bc-11ea-a13a-137349068a90': [120],
             '918d3f50-21bc-11ea-a13a-137349068a90': [119],
             '918d5436-21bc-11ea-a13a-137349068a90': [200],
             '918d5e18-21bc-11ea-a13a-137349068a90': [159],
             '918d92de-21bc-11ea-a13a-137349068a90': [42],
             '918df454-21bc-11ea-a13a-137349068a90': [80],
             '918e12ea-21bc-11ea-a13a-137349068a90': [55],
             '918e9512-21bc-11ea-a13a-137349068a90': [80],
             '918eb5b0-21bc-11ea-a13a-137349068a90': [97],
             '918eb95c-21bc-11ea-a13a-137349068a90': [97],
             '918ec9c4-21bc-11ea-a13a-137349068a90': [175],
             '918f1d16-21bc-11ea-a13a-137349068a90': [55],
             '918fa916-21bc-11ea-a13a-137349068a90': [38],
             '918feafc-21bc-11ea-a13a-137349068a90': [116],
             '918fedfe-21bc-11ea-a13a-137349068a90': [171],
             '9190362e-21bc-11ea-a13a-137349068a90': [69],
             '91908d18-21bc-11ea-a13a-137349068a90': [200],
             '91912458-21bc-11ea-a13a-137349068a90': [93, 197],
             '91914294-21bc-11ea-a13a-137349068a90': [172],
             '9191601c-21bc-11ea-a13a-137349068a90': [39],
             '9191eadc-21bc-11ea-a13a-137349068a90': [93, 93, 130],
             '91923e10-21bc-11ea-a13a-137349068a90': [69],
             '91924734-21bc-11ea-a13a-137349068a90': [36],
             '91925b52-21bc-11ea-a13a-137349068a90': [41, 117, 93],
             '9192f878-21bc-11ea-a13a-137349068a90': [65, 158],
             '919374ce-21bc-11ea-a13a-137349068a90': [172, 32],
             '9193782a-21bc-11ea-a13a-137349068a90': [1, 119],
             '91937e92-21bc-11ea-a13a-137349068a90': [183,
              83,
              122,
              198,
              83,
              104],
             '9193a5a2-21bc-11ea-a13a-137349068a90': [186, 29],
             '9193e4e0-21bc-11ea-a13a-137349068a90': [172],
             '919437c4-21bc-11ea-a13a-137349068a90': [69],
             '91944aa2-21bc-11ea-a13a-137349068a90': [119, 71],
             '91952012-21bc-11ea-a13a-137349068a90': [83],
             '91952cc4-21bc-11ea-a13a-137349068a90': [176],
             '91953e12-21bc-11ea-a13a-137349068a90': [120],
             '9195411e-21bc-11ea-a13a-137349068a90': [10],
             '919547a4-21bc-11ea-a13a-137349068a90': [80],
             '9195c9fe-21bc-11ea-a13a-137349068a90': [196],
             '9195d0fc-21bc-11ea-a13a-137349068a90': [116],
             '919608e2-21bc-11ea-a13a-137349068a90': [190, 193, 189],
             '91960c34-21bc-11ea-a13a-137349068a90': [173],
             '919643e8-21bc-11ea-a13a-137349068a90': [172],
             '9196aaa4-21bc-11ea-a13a-137349068a90': [119],
             '9196ca66-21bc-11ea-a13a-137349068a90': [68],
             '9196e794-21bc-11ea-a13a-137349068a90': [39],
             '91971a84-21bc-11ea-a13a-137349068a90': [91],
             '91972132-21bc-11ea-a13a-137349068a90': [120],
             '91977b8c-21bc-11ea-a13a-137349068a90': [65],

# Create submit file

In [47]:
sub = pd.read_csv(os.path.join(DATASET, 'sample_submission.csv'))
col_Predicted = [col for col in sub.columns if "Predicted" in col]

In [49]:
with fs.open(os.path.join(DATASET, 'metadata/iwildcam2021_train_annotations.json'), encoding='utf-8') as json_file:
    train_annotations =json.load(json_file)
df_categories = pd.DataFrame.from_records(train_annotations["categories"])

For each image, count the number of each animal species and store them in the corresponding column.

In [50]:
results = []

for key in pred.keys():
    c = collections.Counter(pred[key])
    
    res = []
    cnts = [ 0 for i in range(205)]
    for category, cnt in c.items():
        cnts[category] = cnt
    res += [key] + cnts[1:]
    results.append(res)

Convert to pandas dataframe.

In [51]:
sub_tmp = pd.DataFrame(results, columns=sub.columns)

In [52]:
sub_tmp.head()

,Id,Predicted2,Predicted3,Predicted4,Predicted6,Predicted7,Predicted8,Predicted9,Predicted10,Predicted12,...,Predicted559,Predicted562,Predicted563,Predicted564,Predicted565,Predicted566,Predicted567,Predicted568,Predicted570,Predicted571
0,915879a0-21bc-11ea-a13a-137349068a90,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,91588116-21bc-11ea-a13a-137349068a90,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,9158a2f4-21bc-11ea-a13a-137349068a90,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,9158aaa6-21bc-11ea-a13a-137349068a90,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9158f1a0-21bc-11ea-a13a-137349068a90,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [53]:
sub_tmp.to_csv("./sub_tmp.csv", index=False)

Add seq_id information to the counted results. iwildcam2021_test_information.json contains the mapping between the id of the image and the id of the sequence.

In [54]:
with fs.open(os.path.join(DATASET, 'metadata/iwildcam2021_test_information.json'), encoding='utf-8') as json_file:
    test_information =json.load(json_file)
    
df_test_info = pd.DataFrame(test_information["images"])[["id", "seq_id"]]
df_test_info.head()

                                     id                                seq_id
0  8b31d3be-21bc-11ea-a13a-137349068a90  a91ebc18-0cd3-11eb-bed1-0242ac1c0002
1  8cf202be-21bc-11ea-a13a-137349068a90  a91ebc18-0cd3-11eb-bed1-0242ac1c0002
2  8a87e62e-21bc-11ea-a13a-137349068a90  a91ebc18-0cd3-11eb-bed1-0242ac1c0002
3  8e6994f4-21bc-11ea-a13a-137349068a90  a91ebc18-0cd3-11eb-bed1-0242ac1c0002
4  948b29e2-21bc-11ea-a13a-137349068a90  a91ebc18-0cd3-11eb-bed1-0242ac1c0002

Take right join on the image id.

In [55]:
sub_tmp = sub_tmp.merge(df_test_info, left_on="Id", right_on="id", how="right")

In [56]:
sub_tmp.head()

,Id,Predicted2,Predicted3,Predicted4,Predicted6,Predicted7,Predicted8,Predicted9,Predicted10,Predicted12,...,Predicted563,Predicted564,Predicted565,Predicted566,Predicted567,Predicted568,Predicted570,Predicted571,id,seq_id
0,8b31d3be-21bc-11ea-a13a-137349068a90,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8b31d3be-21bc-11ea-a13a-137349068a90,a91ebc18-0cd3-11eb-bed1-0242ac1c0002
1,8cf202be-21bc-11ea-a13a-137349068a90,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8cf202be-21bc-11ea-a13a-137349068a90,a91ebc18-0cd3-11eb-bed1-0242ac1c0002
2,8a87e62e-21bc-11ea-a13a-137349068a90,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8a87e62e-21bc-11ea-a13a-137349068a90,a91ebc18-0cd3-11eb-bed1-0242ac1c0002
3,8e6994f4-21bc-11ea-a13a-137349068a90,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8e6994f4-21bc-11ea-a13a-137349068a90,a91ebc18-0cd3-11eb-bed1-0242ac1c0002
4,948b29e2-21bc-11ea-a13a-137349068a90,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,948b29e2-21bc-11ea-a13a-137349068a90,a91ebc18-0cd3-11eb-bed1-0242ac1c0002

Since there are multiple lines for the same sequence ID. We should aggregate them to single line. In this case, we will choose the image with the highest number of animals shown and submit the animal species and the number of animals shown in that image.

In [57]:
sum_counts = []
for i in range(len(sub_tmp)):
    sum_counts.append(sum(sub_tmp.iloc[i][col_Predicted]))

In [58]:
sub_tmp["total"] =  sum_counts
sub_tmp = sub_tmp.sort_values('total', ascending=False)
sub_tmp = sub_tmp[~sub_tmp.duplicated(keep='first', subset='seq_id')].fillna("0")

In [59]:
sub_tmp

,Id,Predicted2,Predicted3,Predicted4,Predicted6,Predicted7,Predicted8,Predicted9,Predicted10,Predicted12,...,Predicted564,Predicted565,Predicted566,Predicted567,Predicted568,Predicted570,Predicted571,id,seq_id,total
57079,92a85cd0-21bc-11ea-a13a-137349068a90,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,92a85cd0-21bc-11ea-a13a-137349068a90,a91738a8-0cd3-11eb-bed1-0242ac1c0002,10
56856,973b59c8-21bc-11ea-a13a-137349068a90,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,973b59c8-21bc-11ea-a13a-137349068a90,a9173a42-0cd3-11eb-bed1-0242ac1c0002,10
15173,8c37eb40-21bc-11ea-a13a-137349068a90,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,8c37eb40-21bc-11ea-a13a-137349068a90,a9173ae2-0cd3-11eb-bed1-0242ac1c0002,10
42319,91fb2bc8-21bc-11ea-a13a-137349068a90,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,91fb2bc8-21bc-11ea-a13a-137349068a90,a92467da-0cd3-11eb-bed1-0242ac1c0002,10
59874,9903a97c-21bc-11ea-a13a-137349068a90,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,9903a97c-21bc-11ea-a13a-137349068a90,a917398e-0cd3-11eb-bed1-0242ac1c0002,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60115,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,8c3b0424-21bc-11ea-a13a-137349068a90,9500e290-21bc-11ea-a13a-137349068a90,0
60148,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,8d2b546a-21bc-11ea-a13a-137349068a90,386634a2-6fe2-11eb-844f-0242ac1c0002,0
60158,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,902c630c-21bc-11ea-a13a-137349068a90,982a8f20-21bc-11ea-a13a-137349068a90,0
60167,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,867fbf02-21bc-11ea-a13a-137349068a90,92c82344-21bc-11ea-a13a-137349068a90,0
60194,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,94284db8-21bc-11ea-a13a-137349068a90,94284f52-21bc-11ea-a13a-137349068a90,0

I'll match the result to the sample submission format. I was told that the order of the rows is not related to the score, but we will match it just in case.

In [60]:
# Since it was difficult to join the pandas series, I intentionally created an extra column.
sub = sub.reset_index()
sub = sub[["index", "Id"]].merge(sub_tmp, left_on="Id", right_on="seq_id")

In [61]:
sub = sub[["Id_x"] + col_Predicted].rename(columns={"Id_x": "Id"})
sub.to_csv("sub.csv", index=False)

In [62]:
sub.head()

,Id,Predicted2,Predicted3,Predicted4,Predicted6,Predicted7,Predicted8,Predicted9,Predicted10,Predicted12,...,Predicted559,Predicted562,Predicted563,Predicted564,Predicted565,Predicted566,Predicted567,Predicted568,Predicted570,Predicted571
0,32ce8026-7ec9-11eb-b675-4f3cc0c82eb3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,945c6602-21bc-11ea-a13a-137349068a90,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,a91c7e26-0cd3-11eb-bed1-0242ac1c0002,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,9926239e-21bc-11ea-a13a-137349068a90,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9672184c-21bc-11ea-a13a-137349068a90,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
#If we don't delete them, csv files are buried and cannot be retrieved.
!rm -r croped_images_train
!rm -r croped_images_test